### ISSUE TITLE
fueling.json not accepting quantityunitid and fuelsortid as expected

### ISSUE THREAD

**Issue by rolandsteinmeyer** [FundF/Spritmonitor-API-sample-code#1]
https://api.spritmonitor.de/v1/vehicle/1234/tank/1/fueling.json?date=13.04.2023&odometer=27163&trip=25929&quantity=3.33&type=notfull&price=9.99&currencyid=0&pricetype=0&fuelsortid=8&quantityunitid=1

results in:

{
  "errors": 1,
  "errormessages": {
    "base": {
      "quantityunit": {
        "notInArray": "'1' ist ein ungültiger Wert"
      },
      "fuelsort": {
        "notInArray": "'8' ist ein ungültiger Wert"
      }
    }
  }
}

**Comment by FundF** [comment]
This is correct behaviour if the given quantity unit does not match the tank unit (e.g., trying to add liter to a electrity tank, aka the battery).
