### ISSUE TITLE
Export data with API

### ISSUE THREAD

**Issue by Feriman22** [FundF/Spritmonitor-API-sample-code#4]
Hi,

Is it possible to export all the data (fuelings and costs) of a specific car with an API call?

How can I do this? Like here:
![image](https://github.com/FundF/Spritmonitor-API-sample-code/assets/22872515/dd1743f4-28db-44de-b332-7c9aea2874d0)

Thanks,
Feriman

**Comment by FundF** [comment]
No, this is not supported by the API.
